name: "Build|Lint|Test"

on:
  push:
    branches:
      '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: ./login ${{ secrets.NPM_ACCESS_KEY }} ${{ secrets.FONTAWESOME_REGISTRY }}
    - run: export SKIP_PREFLIGHT_CHECK=true
    - run: yarn
    - run: yarn run build 
    - run: yarn run lint
    - run: ROCKSET_APIKEY="${{ secrets.ROCKSET_APIKEY }}" ROCKSET_APISERVER="${{ secrets.ROCKSET_APISERVER }}" yarn run test
      env:
        CI: true
